export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const FILTER_BY_FIRST_OWNER = "FILTER_BY_FIRST_OWNER";
export const FILTER_BY_SECOND_OWNER = "FILTER_BY_SECOND_OWNER";
export const FILTER_BY_THIRD_OWNER = "FILTER_BY_THIRD_OWNER";
export const FILTER_BY_FOURTH_OWNER = "FILTER_BY_FOURTH_OWNER";
export const FILTER_BY_PETROL = "FILTER_BY_PETROL";
export const FILTER_BY_DIESEL = "FILTER_BY_DIESEL";